---
deployment:
  tasks:
    - echo "Starting deployment"
    - export DEPLOYPATH=/home/altaawun/public_html/
    - /bin/cp -R /home/altaawun/altaawun-website/* $DEPLOYPATH
    - echo "Deployment finished"
